@startuml

rectangle "git\ncommit" as commit
rectangle "git\npush" as push
actor bezoeker

rectangle "GitHub" #LightGreen {
rectangle "GitHub Actions\n(Hugo build)" as actions
rectangle "GitHub Actions\n(deploy)" as deploy 
collections "GitHub Pages" as pages
}

commit -right-> push
push -right-> actions
actions -down-> deploy
deploy -down-> pages 
pages -left-> bezoeker 
@enduml